name: CI - Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar códigoo
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
        working-directory: traveltech-multicloud/comments-service

      - name: Ejecutar tests
        run: npm test
        working-directory: traveltech-multicloud/comments-service
            - name: Linter
        run: npm run lint
        working-directory: traveltech-multicloud/comments-service

      - name: Build
        run: npm run build
        working-directory: traveltech-multicloud/comments-service